services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: melbeez
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_service
    ports:
      - "8083:8083"
    depends_on:
      - db

volumes:
  postgres_data: