services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: Melbeez
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network
    volumes:
      - app-db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_service
    ports:
      - 8083:8083
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge
volumes:
  app-db:
    driver: local
